### ISSUE TITLE
Code released

### ISSUE THREAD

**Issue by zhao-yiqun** [yiqun-wang/HFS#2]
Congratulations on your amazing results and acceptance for Neurips 2022,  I wonder what is your code releasing plan, eg. when will you release the code? Can't wait to use your amazing projects! Thank you.

**Comment by yiqun-wang** [comment]
Thank you for your attention, we will release the code soon.

**Comment by zhao-yiqun** [comment]
Hi, I understand that you may be busy with other work, therefore I try to reproduce your work, since it seems not hard based on NeuS. Here summarize a few detail questions, and I hope you can give me some quickly reply :

1).Your paper did not mention about the background modeling as NeuS use a nerf++ for background modeling.  I wonder how you deal with the background in the dataset as DTU at training time.

2).You have implement 2 MLP for SDFnetwork for displacement, I wonder how you deal with them when you implement feed them into the color network for volume rendering. Which density you choose for volume rendering? Or make some combination with both of them?

3). For the sampling strategy, As you mentioned in your paper "then adaptively update the weight according to the gain and sample an additional 64 points". Are these 64 points sampled as Neus did? eg. construct the pdf, and sample the points near the surface. Does it mean you just have changed the Transparency weights using the eq.16 in the paper while other is the same as neus did.

4).  In the eqution 14, why there is a scale term 4 at MLP_d, what will happen if it become larger or smaller, I guess you may try other scales, could you share the design about that?

Sorry for asking so many problems, Since I am following your work and try to extend it for Scene-level reconstruction, I wish you can give me some quick advice. 

Looking forward to your

**Comment by yiqun-wang** [comment]
Thanks for your interest,

1). We use the same way as NeuS to model background,

2). Eq. 14 is used for the combination of two SDFs.

3). Sec. 3.1 shows the difference between others.

4). The term 4 is applied for normalizing the maximum constraint to 1.

We are going to release the cleaned code next week. Cheers.

**Comment by zhao-yiqun** [comment]
Thanks for your quick reply and your code releasing, It made me clear to understand,  And now I will closs the issues, Thank you very much.

**Comment by zhao-yiqun** [comment]
Hi there, 

Will you code be released this week?

Since my reproduced quality is not very well, I need your implementation for refrence, thank you !

Looking forward to your reply

**Comment by zhao-yiqun** [comment]
Following your details in your paper, here is my reproduced results on blended MVS man.
![image](https://user-images.githubusercontent.com/91787021/197105354-f78d4360-02d9-4261-99d3-886e6b690e82.png)
![image](https://user-images.githubusercontent.com/91787021/197105987-8e20c51d-39b4-47d6-bb3d-afa547458e69.png)


Here is the results from NeuS:
![image](https://user-images.githubusercontent.com/91787021/197105893-82ed9ce8-e868-4a7b-9561-b05b4cb10152.png)
![image](https://user-images.githubusercontent.com/91787021/197105997-36feb7d8-cbc1-4a0c-be69-51723c26d24f.png)

The back of the head is not well reconstructed, I think it's some of my missunderstanding for your work, Therefore, I am looking forward to your implementation.

**Comment by yiqun-wang** [comment]
Hi, today I am preparing some important materials to complete neurips requirements. I have cleaned up the code and will release the code tomorrow evening.

**Comment by zhao-yiqun** [comment]
Thanks for your code releasing.
