### ISSUE TITLE
How to get water-tight mesh for evaluation？

### ISSUE THREAD

**Issue by ShadowAQA** [yiqun-wang/HFS#8]
Hi,
Before all, thank you for your inspiring work !
I can get the mesh file through this job, I would like to know what tool you use to get the water-tight mesh.
for example：
 
![fig2](https://user-images.githubusercontent.com/103158333/220136012-03557950-766e-4cc8-946b-78029ab61a6f.png)

**Comment by yiqun-wang** [comment]
Hello, from the current point of view, it is unlikely to fully guarantee the watertight property for complex models like this house model. Especially when only part of the model is scanned.

**Comment by ShadowAQA** [comment]
Thanks for your reply, I will close this issue.
